apiVersion: v1
kind: Service
metadata:
  name: zevrant-acra-backend
spec:
  ports:
    - port: 443
      targetPort: 9008
  selector:
    app: zevrant-acra-backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-acra-backend-deployment
  labels:
    app: zevrant-acra-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zevrant-acra-backend
  template:
    metadata:
      labels:
        app: zevrant-acra-backend
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        architecture: amd64
      containers:
        - name: zevrant-acra-backend
          image: docker.io/zevrant/zevrant-acra-backend:$VERSION
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: zevrant-acra-backend-aws
                  key: username
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: zevrant-acra-backend-aws
                  key: password
            - name: ENVIRONMENT
              value: $ENVIRONMENT
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 9008
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-acra-backend/actuator/health
              port: 9010
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-acra-backend/actuator/health
              port: 9010
            initialDelaySeconds: 10
