version: '3.5'
services:
  zevrant-acra-service-db:
    ports:
      - "5440:5432"
    image: postgres:latest
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: example
      POSTGRES_DB: acra


