server:
  ssl:
    key-store: /usr/local/microservices/zevrant-home-services/zevrant-acra-backend/zevrant-services.p12
    key-store-type: PKCS12
    key-store-password: ${password}

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://develop.zevrant-services.com/auth/realms/zevrant-services
  datasource:
    url: jdbc:postgresql://zevrant-acra-backend-db:5432/acra?createDatabaseIfNotExist=true
    username: 'zevrant'
    password: ${rds.acra.password}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

zevrant:
  services:
    notification: https://zevrant-notification-service/zevrant-notification-service
